---

- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Assure awx is installed
    kubernetes.core.helm:
      name: awx-operator
      chart_repo_url: "https://ansible.github.io/awx-operator/"
      chart_ref: awx-operator
      release_namespace: default
      release_state: present
    register: result
  - name: Assure awx is installed
    ansible.builtin.assert:
      that: 
      - result.status.status == "deployed"
